os: linux
dist: xenial
language: php

# PHP version used in first build configuration.
php:
    - "7.4"
    - "7.3"
    - "7.2"

# WordPress version used in first build configuration.
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=5.4.2 WP_MULTISITE=0
    - WP_VERSION=5.4.2 WP_MULTISITE=1
    - WP_VERSION=5.5 WP_MULTISITE=0
    - WP_VERSION=5.5 WP_MULTISITE=1

services:
    - mysql

install:
    - npm install
    - composer require --dev phpunit/phpunit ^7

# Clones WordPress and configures our testing environment.
before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PLUGIN_SLUG=$(basename $(pwd))
    - cd ..
    - mv $PLUGIN_SLUG "/tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG"
    - cd "/tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG"

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
    apt: true
    directories:
        - $HOME/.npm
        - vendor
        - $HOME/.composer/cache
